import React from 'react'

const LoadingWorkout = () => {
  return (
    <div className='loading'>
     WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...WORKOUT...
    </div>
  )
}

export default LoadingWorkout